
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=RailScope;encrypt=false
spring.datasource.username=sa
spring.datasource.password=A850107a
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.mia.railscopeapi.model

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
